// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaz1HoDpZxb584tFIAMhHiaz5ORSD0TYk',
    appId: '1:975726861063:web:393a1548c3e686091083a2',
    messagingSenderId: '975726861063',
    projectId: 'accuchat-d5e99',
    authDomain: 'accuchat-d5e99.firebaseapp.com',
    databaseURL: 'https://accuchat-d5e99-default-rtdb.firebaseio.com',
    storageBucket: 'accuchat-d5e99.firebasestorage.app',
    measurementId: 'G-DNKJ4PP5MZ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCWVUwdH6AFLrrAXp8VL0O_StAkYuWgCY',
    appId: '1:975726861063:ios:2c2e871b09507b3f1083a2',
    messagingSenderId: '975726861063',
    projectId: 'accuchat-d5e99',
    databaseURL: 'https://accuchat-d5e99-default-rtdb.firebaseio.com',
    storageBucket: 'accuchat-d5e99.firebasestorage.app',
    androidClientId: '975726861063-c99qkseb9iqi6s8nl9h9hnghkvmdesse.apps.googleusercontent.com',
    iosClientId: '975726861063-2tup6bmqf9gmbl6k0ckb94tftjpg9jmf.apps.googleusercontent.com',
    iosBundleId: 'com.app.accuChat',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSAwm0Ro420zfkcBnViLU7xdy8SfU6ImA',
    appId: '1:975726861063:android:b0f2917d0dbe74221083a2',
    messagingSenderId: '975726861063',
    projectId: 'accuchat-d5e99',
    databaseURL: 'https://accuchat-d5e99-default-rtdb.firebaseio.com',
    storageBucket: 'accuchat-d5e99.firebasestorage.app',
  );

}